name: Builds

on:
  push:
  schedule:
    - cron: '15 7 * * *'

jobs:
  build_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        type: [native, emscripten]
        exclude:
        - os: ubuntu-latest
          type: emscripten
        - os: macos-latest
          type: emscripten

    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
      if: matrix.os == 'windows-latest'
    - name: Execute
      id: build
      uses: nicozink/github-build-actions@master
      with:
        os: ${{ matrix.os }}
        project_root: ${{ github.event.repository.name }}
        type: ${{ matrix.type }}